{% set name = "flatten-dict" %}
{% set version = "0.5.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name | replace('-', '_') }}-{{ version }}.tar.gz
  sha256: ca89664d0bc9552d525ee756726b5a755c17f65b5bf23d0a1f07841f181428b7

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
    - poetry
  run:
    - pathlib2 >=2.3,<3.0
    - python >=3.6
    - setuptools
    - six >=1.12,<2.0

test:
  requires:
    - pip
  imports:
    - flatten_dict
    - flatten_dict.tests
  commands:
    - pip check

about:
  home: https://github.com/ianlini/flatten-dict
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: A flexible utility for flattening and unflattening dict-like objects in Python.

extra:
  recipe-maintainers:
    - bgruening
    - efiop
